name: Terraform CI/CD

on:
  pull_request:
    paths:
      - '**/*.tf'
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.3.7  # Set the desired Terraform version

    - name: Install Checkov
      run: |
        pip install checkov

    - name: Install TFLint
      run: |
        curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Run Checkov - Terraform Static Analysis
      run: checkov -d .

    - name: Run TFLint - Terraform Linter
      run: tflint

    - name: Terraform Plan
      run: terraform plan -out=tfplan

    - name: Upload Terraform Plan
      uses: actions/upload-artifact@v2
      with:
        name: terraform-plan
        path: tfplan

